version: '3.5'

services:
  contactmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  reportmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

